### ISSUE TITLE
Action Test

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#10]
## Reason

There are two types of tests in Earthdawn. Effect tests (see Epic Effect Tests) and Action tests. The following test shall be covered in this Epic:
- [ ] Attribute Test
- [ ] Talent Tests
- [ ] Skill Tests
- [ ] Devotion Tests
- [ ] Knack Tests
  - [ ] Knack Tests with Standard Effects
- [ ] Spell casting Tests
- [ ] Thread Weaving (Attune Matrix on the fly) Tests
- [ ] Thread Weaving (weave threads to matrix) Tests
- [ ] Raw Magic casting Tests
- [ ] Grimoire casting Tests
- [ ] Reaction Tests
- [ ] Half-magic Tests
- [ ] Roll-able Item Tests (unclear use case)
- [ ] Attack Tests
  - [ ] Ranged Weapon attack Tests
  - [ ] Melee Weapon attack Tests
  - [ ] unarmed Weapon attack Tests
  - [ ] Thrown Weapon attack Tests
  - [ ] Creature Attack-Power melee attack Tests
  - [ ] Creature Attack-Power ranged attack tests
  - [ ] Creature Power-Power melee attack Tests
  - [ ] Creature Power-Power ranged attack tests
 - [ ] Jump up Test
 - [ ] Knock down Test

## Proposed Solution

for a differentiation between all those action tests, my suggestion is to use a reoccurring attribute which can be declared at a global place like **rollType**.
The rolltype could be handed over in each function as input parameter and therefore easily used to differentiate the use cases.
