### ISSUE TITLE
difficulty and success of rolls

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#113]
Difficulties shall be used for evaluation if, a roll is successful, not successful and how many extra successes where achieved.

the difficulty of the roll prompt shall be evaluated by the item used for the roll (see #126 ) 
- [ ] the diffculty shall be updatable by the selection of the roll prompt (see #64 ) #127 
- [ ] the value from the roll prompt (see #64 ) shall be used as difficulty.  #114 
- [ ] basic success is reached if the roll result is >= the difficulty #115 
- [ ] extra successes are calculated: Roll result - difficulty / 5 #116 
- [ ] the Result shall be part of the chat-output #117

**Comment by patrickmohrmann** [comment]
duplicate / Done
