### ISSUE TITLE
chat output

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#117]
Chat output shall show the result of every roll:

the following information shall be part of every chat output:

- [ ] Name of source actor ( #119 )
- [ ] Name of target(s) ( #119 )
- [ ] karma usage ( #119 )
- [ ] devotion usage ( #119 )
- [ ] roll result ( #119 )
- [ ] roll step ( #119 )
- [ ] extra dice (steps) ( #119 )
- [ ] active mods #121 
- [ ] roll result #123 
- [ ] change roll result (GM) #124 
- [ ] extra successes ( #119 )
- [ ] apply damage #120 
- [ ] apply effect #121 
- [ ] use reaction #122
