### ISSUE TITLE
[itemSheet] - Discipline

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#12]
## Reason

The discipline item is one of the main items of each PC. There are basically three types of Discipline. the original Disciplin with 15 Circles, the Path with 5 to 10 ranks and the Questor with 12 Ranks.

besides the different number, the differences are pretty small and will be handled in one sheet. the following information will describe the general fields:

- [ ] name (string)
- [ ] type (drop down selection - Discipline, Path, Questor)
- [ ] description section (Editor)
- [ ] Game details (Editor)
- [ ] maximum Rank/circle (number)

based on the maximum Rank/Cicle input there will be additional tabs (maximum 15) available. each one containing:
- [ ] number (number)
- [ ] optional Abilities (every 4 ranks/circle will show up a new one - novice 1-4; journeymen 5-8, warden 9-12, master 13-5)
- [ ] one add button for Characteristic change
- [ ] one add button for special ability

Disciplines will have the following additional Options:
- [ ] Durability (number)
- [ ]
