### ISSUE TITLE
Step to dice conversion

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#129]
## Reason

over the several editions. Earthdawn faced several different step tables. there shall be a system setting to chose the step table.

In addition to this simple selection. a function shall be created which will transform the final step of a roll into a dice string

## Proposed Solution

- [ ] System settings for first Edition Dice
- [ ] System settings for second Edition Dice
- [ ] System settings for third Edition Dice
- [ ] System settings for fourth Edition Dice
- [ ] step conversion into string function
