### ISSUE TITLE
LP Tracking (WIP)

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#14]
## Reason

LP tracking is a major part of the evolvment of a character

## Proposed Solution

- [ ] automatic status calculation
- [ ] chat message to include in adventures like those of Warhammer4e system
- [ ] Dragging Talents / skills / devotions / Spells / Matrices onto the charactersheet will cause a prompt asking ( if it is free or shall cost XP) in case of talents it will ask in addition to select the subtype (discipline, free, versatility, race)
