### ISSUE TITLE
Earthdawn Tour

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#16]
## Reason

each finished feature shall have its own tour. this is the first idea of an order:

GM Tour:
- [ ] System settings
- [ ] Request Roll
- [ ] Combat tracker
- [ ] Mask creation
- [ ] damage roll changes

Player & GM tour:
- [ ] Charakter generation
- [ ] Item types (each type one Tour)
- [ ] Spell casting workflow (Raw, Grimoire, Matrix)
- [ ] Combat
- [ ] EAEs
- [ ] LP Tracking
