### ISSUE TITLE
[actorSheet] - PC - basics

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#17]
## Reason

basic framework of the sheet

## Solution details

mock up 
![image](https://github.com/patrickmohrmann/earthdawn4eV2/assets/76265425/72e45095-a7a8-4192-a202-826d5035b5d9)

## Technical details

- [ ] automatic Frame size change based on Font size configuration
- [ ] similar margin around each element
- [ ] tab details has its own scrollbar

### Open topics
Flex or Grit

**Comment by patrickmohrmann** [comment]
done
