### ISSUE TITLE
Attribute Workflows

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#182]
attribute tests are pretty basic.
clicking on the attribute name a roll-prompt will open:
- [x] the roll prompt needs to get the following data (see #64 )
  - [x] rollType = "attribute"
  - [x] baseStep = "baseStep (see #51 )
  - [x] actorData = preparedData + baseData
  - [x] activeMods = activeMods [Array]

after all information are handed over to the roll-prompt and the calculations are done, the final step, karma, devotions etc. will be resolved in the following stories:
- [x] Step do dice conversion #129 

all outputs are handed over to the rollDice function, where all inputs are evaluated.
- [x] evaluateRoll #113 
- [x] #191
- [x] #192
- [x] #193

the result will be send to the chat
- [x] #170
