### ISSUE TITLE
Combat / Situation Modifier on Sidebar

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#20]
## Reason

Earthdawn has several situational and combat specific modifiers. These Modifiers shall be accessible via each Actor sheet as a Sidebar option on the right side. In addition, those options shall be presented at each token.

## Proposed Solution

- [ ] create Quick Access Combat / Situation Modifier Sidebar
  - [ ] include an Option for **On and OFF** Modifier (Aggressive Attack)
  - [ ] include an Option for **ON and X additional Times affected** Modifier (Harried + Overwhelmed) 
  - [ ] include options for **50% and 100%**

The following options shall be available (probably in that order):
- [ ] Aggressive Attack
- [ ] Defensive Stance
- [ ] Knocked Down
- [ ] Harried
- [ ] Blindsided
- [ ] Cover 
- [ ] Darkness
- [ ] Impaired Movement
- [ ] Surprised
