### ISSUE TITLE
Replace Existing Earthdawn4e System

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#21]
## Reason

this Epic shall cover everything from migrate user Data to exchange the system availability in Foundry

### Module Migration

- [ ] migrate Items
  - [ ] Talents
  - [ ] Knacks
  - [ ] Spells
  - [ ] Devotion
  - [ ] Skills
  - [ ] Equipment
  - [ ] Weapons
  - [ ] Armor
  - [ ] Shields
  - [ ] Attacks
  - [ ] Masks (Might be Manual)
  - [ ] Disciplines (Might be Manual)
  - [ ] Namegiver (Might be Manual)
- [ ] migrate Actors
  - [ ] PC
  - [ ] NPC
  - [ ] Creatures

### Replace System in Foundry
- [ ] include a new Earthdawn System

#### English Modules

- [ ] Players Guide
- [ ] Game Masters Guide
- [ ] Compendium
- [ ] Mystic Paths
- [ ] Questors
- [ ] Legends of Barsaive 1
- [ ] Deeper Secrets
- [ ] Iopos City of Deceit
- [ ] Vasgothia

#### German Modules

- [ ] Spielerhandbuch
- [ ] Spielleiterhandbuch
- [ ] Kompendium
- [ ] Mystische Pfade
- [ ] Questoren
- [ ] Legenden von Barsaive 1: Haven
- [ ] Legenden von Earthdawn 1
- [ ] Kaers
- [ ] Elfennationen
- [ ] Barsaive Box
- [ ] Nebel über dem Blutwald
- [ ] Geißel des HImmels
- [ ] Tanz mit der Schlange
