### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#370]
all tokens shall have the following settings:

- [ ] default Resource 1:
  - total Damage / Death Rating
  - changing color from 0 = green to Death Rating = Red
- [ ] default Resource 2:
  - Karma current / Karma total

- [ ] all conditions from the data model shall be accessible via the token "assign status effect" option.
- [ ] a would shall show a small blood drop on the icon with a number inside showing the total number of wounds 

- [ ] check foundry basic effects, and keep those releveant (like invisibility)

### Character specific

the following settings shall be specific for actors of type character:
- [ ] Has Vision = yes
- [ ] Linked Token = yes

**Comment by patrickmohrmann** [comment]
done
