### ISSUE TITLE
Chat output - Rolls

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#403]
the message output of any roll shall contain the following information:
- [x] user Image (either from the user configuration, system setting or owned/selected token)
- [x] executer name (token name)
- [ ] ~roll type (melee attack, spellcasting, talent roll etc)~ #478 
- [ ] ~action type (effect roll, action roll, arbitrary roll)~ #478
- [x] a drop down option to see al modifieres relevant for the calculation (see old system)
- [ ] ~roll result (including successes if difficulty is != 0)~ see #465 
- [x] dice results
- [x] option buttons to assign effects, roll damage, assign damage etc.
