### ISSUE TITLE
Item Type Armor

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#422]
armor items shall have the following data available
- [x] physical armor 
- [x] mystical armor
- [x] physical forge bonus
- [x] mystical forge bonus
- [x] initiative penalty
- [x] cost
- [x] weight
- [x] availability
- [x] description

further armor items shall contain detail information:
- [x] usable item
  - [x] arbitrary step
  - [x] action type
- [x] blood magic damage
- [x] weight modifier option

## functionality
armor has the following functionalities:
- [x] **physical protection.** if damage is assigned and has the physical indicator. the damage is reduced by the amount of the **physical armor value + physical forge bonus value**
- [x] **mystical protection.** if damage is assigned and has the mystical indicator. the damage is reduced by the amount of the **mystical armor value + mystical forge bonus value**
- [x] **Encumbrance**. the Weight value shall be added to the total encumbrance of the actor
- [x] **initiative penalty.** the initiative penalty value shall - if equipped - reduce the initiative value of the actor
- [x] **usable actions.** if the usable checkbox is true, the armor item in the actor sheet becomes a clickable item (see #614 )
- [x] **Thread item.** if the item becomes a Thread item, it shall be able to hold any number of threads (see #443 )
- [x] **EAE.** the item shall be able to hold active effects (see #408  )
