### ISSUE TITLE
Workflow Roll Talent

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#423]
- [x] it shall be possible to trigger the usage of a talent by clicking the talent dice symbol.  (#232 )

this shall trigger a roll prompt.

- [x] difficulty calculation shall be based on the talent setting (#250 )

- [x] talents of type "Versatility" will by default not allow the usage of karma, only special abilities might allow that. a mapping table should be created to get an overview  (moved to feature backlog #701 )

**Comment by patrickmohrmann** [comment]
open issue moved to feature backlog
