### ISSUE TITLE
Workflow Roll skill

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#425]
- [x] it shall be possible to trigger the usage of a skill by clicking the skill dice symbol. (done with #232 )
- [x] difficulty caluclation (done with #250 )
this shall trigger a roll prompt.

- [ ] skills will by default not allow the usage of karma, only special abilities might allow that. a mapping table should be created to get an overview (moved to feature backlog with story #704 )

**Comment by patrickmohrmann** [comment]
open topic moved to feature backlog
