### ISSUE TITLE
[System Setting] - Dark Mode

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#512]
The System shall be usable in either a dark mode or a light mode (default) for this, a system setting was included which shall have the following properties:
- [ ] A slider with steps from 1-10 going from light background and dark letters to dark background and light letters
- [x] The setting has to be client specific.

with the setting of the dark mode system setting slider the following pieces/areas of the application are affectd:

- [x] Actor Sheet (all Types)
- [ ] Journal entries
- [x] Item Sheets (all Types)
- [x] GUI

**Comment by patrickmohrmann** [comment]
This shall be obsolete with AppV2
