### ISSUE TITLE
Create Spell DataModel

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#560]
**Description**
Create Spell DataModel
include the following information:
- [ ] Thread
- [ ] Weaving difficulty
- [ ] reattuning difficulty
- [ ] casting difficulty
- [ ] range
  - [ ] range UOM (unit of measure)
  - [ ] range value
- [ ] duration 
  - [ ] duration UOM
  - [ ] duration value
- [ ] Effect 
- [ ] Area of effect
  - [ ] Area of effect UOM
  - [ ] Area of Effect value
- [ ] shared matrix space (see Ephemeral Bolt and true Ephemeral Bolt of the illusionist, they share a matrix space)
- [ ] extra threads (see #883 )
- [ ] extra successes (see #883 )
- [ ] keywords (see #477 ) (potentially to be done later)

**Additional context**
