### ISSUE TITLE
[itemSheet] - Namegiver

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#6]
# Epic

###Unsolved Dependencies
#57 Keywords
#56 Specials 
#55 EAE

## Reason

the Namegiver Item shall contain the following:

- [ ] contain Attribute-value bonus
- [ ] contain movement base value
- [ ] contain karma base value
- [ ] contain a description
- [ ] contain a area for specials (same as for EAE's)
- [ ] contains area for active effects (for characteristics)
- [ ] contains weapon size Restrictions
- [ ] randomQuotes

#### Sheet design
#61 Create Namegiver Sheet (hbs)

#### CSS design
#62 Create Namegiver Sheet (CSS)

#### embed functionality
#63 create Namegiver Sheet functions (js)

## Proposed Solution

nice cover page --- some css fun---

![image](https://github.com/patrickmohrmann/earthdawn4eV2/assets/76265425/8875b708-0974-40d5-a88e-63eeac60a689)

a few necessary js functions are included in the hbs. file as comments 
[namegiver-sheet-and-style.zip](https://github.com/patrickmohrmann/earthdawn4eV2/files/12707289/namegiver-sheet-and-style.zip)

### fields/Areas

- attribute base values [number]
- Karma modifier [number]
- Movement base value [number]
- Movement fly value (could be made optional) [number]
- list of effects (EAE - all permanent) [Array] 
- list of special & Talents [Array]
- list of keywords [Array]
- Weapon Size one handed [number]
- Weapon Size two handed [number]
- description [editor]
- random QUotes [editor]
- Cover image [img]
- Characterimage [img]
- Name [string]

### specials
a list of specials and talents to be added later on to the actor.

### EAE

as active effects.

### Keywords

a list of keywords, unclear how to add them at the moment,

**Comment by patrickmohrmann** [comment]
done / duplicate
