### ISSUE TITLE
create history entries for manual editing the spend and total LP fields

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#624]
**Description**
in terms of an easy way to work with LP tracking and avoid user struggles it has to be possible to change the Legend Point fields manually and by that creating automatically entries in the history (spend and earned)

- [ ] by manually updating the total field, a new entry in the history - earned will be created with the description "manual entry" and the according LPs

- [ ] by manually updating the spend field, a new entry in the history - spend will be created with the description "manual entry" and the according LPs

- [ ] the field current has to go to read only

**Additional context**
