### ISSUE TITLE
LP tracking - History and overview dialog

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#80]
**Description**
a dialog shall be available to show all spend Legend Points. There shall be several options in this:

- [ ] Date/Time of spending
- [ ] Object
- [ ] Spend LP
- [ ] Total LP before
- [ ] Total LP after
- [ ] Previous value 
- [ ] Value after increase
- [ ] ...

It would be great if the list would be sorted and folded in by Object
e.g.
Melee weapons 1-2
Melee Weapons 2-3
Dexterity 14-15
Dexterity 15 - 16

in each of those clusters it should be possible to delete the latest entry, which will refund the spend LP

refunding LP shall be a system setting which will have a toggle to be done by GM only or by Players as well.

**Additional context**

**Comment by patrickmohrmann** [comment]
done / duplicate
